<script lang="ts">
  import {
    iconStyle,
    mergeClassNames,
    resolveIconKind,
    type Icon as IconType,
    type IconInterface,
    type SvgImport,
  } from '@udixio/core';
  import { createStyle } from '../utils/create-style.svelte';
  import type { SvelteIconProps } from './icon.types';

  type FontAwesomeIcon = Exclude<IconType, string | SvgImport>;

  let { icon, colors = [], class: hostClass = '', classes }: SvelteIconProps = $props();

  const kind = $derived(resolveIconKind(icon));

  // Raw SVG strings are trusted static assets generated by @udixio/icons-*
  // and never carry their own `fill`, so the `fill-current` class plus the
  // inherited `color` style already theme every path via `currentColor`.
  const rawSvg = $derived(
    typeof icon === 'string'
      ? icon.replace(/<svg([^>]*)>/, (_match, attributes: string) => {
          const cleanAttributes = attributes.replace(/\s+(width|height)=["'][^"']*["']/g, '');
          return `<svg${cleanAttributes} width="100%" height="100%">`;
        })
      : '',
  );
  const svgImport = $derived(icon as SvgImport);
  const fontAwesome = $derived(icon as FontAwesomeIcon);
  const viewBox = $derived(`0 0 ${fontAwesome.icon?.[0]} ${fontAwesome.icon?.[1]}`);
  const paths = $derived.by(() => {
    const pathData = fontAwesome.icon?.[4];
    return typeof pathData === 'string' ? [pathData] : (pathData ?? []);
  });

  const styles = createStyle(iconStyle, () => ({
    icon,
    colors,
    className: mergeClassNames<IconInterface>('icon', classes, hostClass),
  }));
</script>

{#if kind === 'raw'}
  <span aria-hidden="true" class={styles.current['icon']} style:color={colors[0] || undefined}>
    <!-- eslint-disable-next-line svelte/no-at-html-tags -- a raw SVG string is a trusted static asset produced by @udixio/icons-*, rendered the same way by React (dangerouslySetInnerHTML) and Angular (bypassSecurityTrustHtml). -->
    {@html rawSvg}
  </span>
{:else if kind === 'image'}
  <img
    alt=""
    aria-hidden="true"
    class={styles.current['icon']}
    src={svgImport.src}
    width={svgImport.width}
    height={svgImport.height}
    style:filter={colors[0] ? 'brightness(0) saturate(100%) invert(1)' : undefined}
  />
{:else}
  <svg
    xmlns="http://www.w3.org/2000/svg"
    role="img"
    aria-hidden="true"
    class={styles.current['icon']}
    viewBox={viewBox}
    style:color={colors[0] || undefined}
    style:--fa-primary-color={colors[0] || undefined}
    style:--fa-secondary-color={colors[1] || undefined}
  >
    {#each paths as path (path)}
      <path class="fill-current" d={path} />
    {/each}
  </svg>
{/if}
