import {
  ChangeDetectionStrategy,
  Component,
  computed,
  inject,
  input,
} from '@angular/core';
import { DomSanitizer, type SafeHtml } from '@angular/platform-browser';
import {
  iconStyle,
  resolveIconKind,
  type Icon as IconType,
  type SvgImport,
} from '@udixio/core';
import { createStyle } from '../utils/create-style';

type FontAwesomeIcon = Exclude<IconType, string | SvgImport>;

@Component({
  selector: 'udx-icon',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: 'display: contents' },
  template: `
    @switch (kind()) {
      @case ('raw') {
        <span
          aria-hidden="true"
          [class]="styles()['icon']"
          [style.color]="colors()[0] || null"
          [innerHTML]="rawSvg()"
        ></span>
      }
      @case ('image') {
        <img
          alt=""
          aria-hidden="true"
          [class]="styles()['icon']"
          [src]="svgImport().src"
          [width]="svgImport().width"
          [height]="svgImport().height"
          [style.filter]="
            colors()[0] ? 'brightness(0) saturate(100%) invert(1)' : null
          "
        />
      }
      @case ('fontawesome') {
        <svg
          xmlns="http://www.w3.org/2000/svg"
          role="img"
          aria-hidden="true"
          [class]="styles()['icon']"
          [attr.viewBox]="viewBox()"
          [style.color]="colors()[0] || null"
          [style.--fa-primary-color]="colors()[0] || null"
          [style.--fa-secondary-color]="colors()[1] || null"
        >
          @for (path of paths(); track $index) {
            <path class="fill-current" [attr.d]="path" />
          }
        </svg>
      }
    }
  `,
})
export class Icon {
  readonly icon = input.required<IconType>();
  readonly colors = input<readonly string[]>([]);
  readonly className = input<string>();

  protected readonly kind = computed(() => resolveIconKind(this.icon()));

  private readonly sanitizer = inject(DomSanitizer);

  /** Raw SVG strings are trusted static assets generated by @udixio/icons-*. */
  protected readonly rawSvg = computed<SafeHtml>(() => {
    const icon = this.icon();
    if (typeof icon !== 'string') return '';

    const normalizedSvg = icon.replace(
      /<svg([^>]*)>/,
      (_match, attributes: string) => {
        const cleanAttributes = attributes.replace(
          /\s+(width|height)=["'][^"']*["']/g,
          '',
        );
        return `<svg${cleanAttributes} width="100%" height="100%">`;
      },
    );

    return this.sanitizer.bypassSecurityTrustHtml(normalizedSvg);
  });

  protected readonly svgImport = computed(() => this.icon() as SvgImport);
  private readonly fontAwesome = computed(
    () => this.icon() as FontAwesomeIcon,
  );
  protected readonly viewBox = computed(() => {
    const [width, height] = this.fontAwesome().icon;
    return `0 0 ${width} ${height}`;
  });
  protected readonly paths = computed(() => {
    const pathData = this.fontAwesome().icon[4];
    return typeof pathData === 'string' ? [pathData] : pathData;
  });

  protected readonly styles = createStyle(iconStyle, () => ({
    icon: this.icon(),
    colors: this.colors(),
    className: this.className(),
  }));
}
