import {
  ChangeDetectionStrategy,
  Component,
  computed,
  inject,
  input,
} from '@angular/core';
import { DomSanitizer, type SafeHtml } from '@angular/platform-browser';
import {
  classNames,
  type Icon as IconType,
  type SvgImport,
} from '@udixio/core';

type IconKind = 'raw' | 'image' | 'fontawesome';
type FontAwesomeIcon = Exclude<IconType, string | SvgImport>;

@Component({
  selector: 'lib-icon',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: 'display: contents' },
  template: `
    @switch (kind()) {
      @case ('raw') {
        <span
          aria-hidden="true"
          [class]="classes(true)"
          [style.color]="colors()[0] || null"
          [innerHTML]="rawSvg()"
        ></span>
      }
      @case ('image') {
        <img
          alt=""
          aria-hidden="true"
          [class]="classes(false)"
          [src]="svgImport().src"
          [width]="svgImport().width"
          [height]="svgImport().height"
        />
      }
      @case ('fontawesome') {
        <svg
          xmlns="http://www.w3.org/2000/svg"
          role="img"
          aria-hidden="true"
          [class]="classes(false)"
          [attr.viewBox]="viewBox()"
          [style.color]="colors()[0] || null"
          [style.--fa-primary-color]="colors()[0] || null"
          [style.--fa-secondary-color]="colors()[1] || null"
        >
          @for (path of paths(); track $index) {
            <path class="fill-current" [attr.d]="path" />
          }
        </svg>
      }
    }
  `,
})
export class Icon {
  readonly icon = input.required<IconType>();
  readonly colors = input<readonly string[]>([]);
  readonly className = input<string>();

  protected readonly kind = computed<IconKind>(() => {
    const icon = this.icon();
    if (typeof icon === 'string') return 'raw';
    return 'src' in icon ? 'image' : 'fontawesome';
  });

  private readonly sanitizer = inject(DomSanitizer);

  /** Raw SVG strings are trusted static assets generated by @udixio/icons-*. */
  protected readonly rawSvg = computed<SafeHtml>(() => {
    const icon = this.icon();
    if (typeof icon !== 'string') return '';

    const normalizedSvg = icon.replace(
      /<svg([^>]*)>/,
      (_match, attributes: string) => {
        const cleanAttributes = attributes.replace(
          /\s+(width|height)=["'][^"']*["']/g,
          '',
        );
        return `<svg${cleanAttributes} width="100%" height="100%">`;
      },
    );

    return this.sanitizer.bypassSecurityTrustHtml(normalizedSvg);
  });

  protected readonly svgImport = computed(() => this.icon() as SvgImport);
  private readonly fontAwesome = computed(() => this.icon() as FontAwesomeIcon);
  protected readonly viewBox = computed(() => {
    const [width, height] = this.fontAwesome().icon;
    return `0 0 ${width} ${height}`;
  });
  protected readonly paths = computed(() => {
    const pathData = this.fontAwesome().icon[4];
    return typeof pathData === 'string' ? [pathData] : pathData;
  });

  protected classes(raw: boolean): string {
    return classNames(
      'size-5 box-content',
      raw && 'inline-flex fill-current',
      this.className(),
    );
  }
}
