import type React from 'react';
import { IconDefinition } from '@fortawesome/fontawesome-svg-core';
import {
  iconStyle,
  resolveIconKind,
  type Icon as IconType,
  type SvgImport,
} from '@udixio/core';
import { createUseStyle } from '../utils/create-use-style';

export type Icon = IconType;

interface Props {
  icon: Icon;
  colors?: string[];
  className?: string;
}

export const useIconStyle = createUseStyle(iconStyle);

export const Icon: React.FC<Props> = ({
  icon,
  colors = [],
  className,
  ...restProps
}) => {
  const kind = resolveIconKind(icon);
  const styles = useIconStyle({ icon, colors, className });

  // Raw SVG strings are trusted static assets generated by @udixio/icons-*
  // and never carry their own `fill`, so the `fill-current` class plus the
  // inherited `color` style below already theme every path via `currentColor`.
  if (kind === 'raw') {
    const svgContent = (icon as string).replace(
      /<svg([^>]*)>/,
      (_match, attributes: string) => {
        const cleanAttributes = attributes.replace(
          /\s+(width|height)=["'][^"']*["']/g,
          '',
        );
        return `<svg${cleanAttributes} width="100%" height="100%">`;
      },
    );

    return (
      <span
        aria-hidden="true"
        className={styles.icon}
        style={{ color: colors[0] || undefined }}
        dangerouslySetInnerHTML={{ __html: svgContent }}
      />
    );
  }

  if (kind === 'image') {
    const svgImport = icon as SvgImport;
    return (
      <img
        src={svgImport.src}
        width={svgImport.width}
        height={svgImport.height}
        className={styles.icon}
        style={{
          filter: colors[0]
            ? `brightness(0) saturate(100%) invert(1)`
            : undefined,
        }}
        alt=""
        aria-hidden="true"
      />
    );
  }

  const faIcon = icon as IconDefinition;
  if (!faIcon?.prefix) {
    throw new Error(`Invalid icon type: ${typeof icon}`);
  }

  const { icon: iconData } = faIcon;
  const [width, height, , , svgPathData] = iconData || [];

  const getColorStyle = (): React.CSSProperties => {
    switch (colors.length) {
      case 2:
        return {
          '--fa-primary-color': colors[0] || 'inherit',
          '--fa-secondary-color': colors[1] || 'inherit',
        } as React.CSSProperties;
      case 1:
        return { color: colors[0] } as React.CSSProperties;
      default:
        return {};
    }
  };

  return (
    <svg
      className={styles.icon}
      style={{ ...getColorStyle() }}
      xmlns="http://www.w3.org/2000/svg"
      viewBox={`0 0 ${width} ${height}`}
      role="img"
      aria-hidden="true"
      {...restProps}
    >
      {typeof svgPathData === 'string' ? (
        <path className={'fill-current'} d={svgPathData} />
      ) : (
        svgPathData.map((d, index) => <path key={index} d={d} />)
      )}
    </svg>
  );
};
